# Generated by Django 5.2.7 on 2025-10-16 16:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('metric_type', models.CharField(choices=[('count', 'Count'), ('percentage', 'Percentage'), ('currency', 'Currency')], default='count', max_length=20)),
                ('value', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Key Performance Indicator',
                'verbose_name_plural': 'Key Performance Indicators',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True)),
                ('total_users', models.PositiveIntegerField(default=0)),
                ('total_contacts', models.PositiveIntegerField(default=0)),
                ('total_opportunities', models.PositiveIntegerField(default=0)),
                ('total_tasks', models.PositiveIntegerField(default=0)),
                ('deals_won', models.PositiveIntegerField(default=0)),
                ('deals_lost', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Analytics Snapshot',
                'verbose_name_plural': 'Analytics Snapshots',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='analytics_a_date_ca2b97_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserPerformance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('contacts_created', models.PositiveIntegerField(default=0)),
                ('opportunities_created', models.PositiveIntegerField(default=0)),
                ('tasks_completed', models.PositiveIntegerField(default=0)),
                ('deals_closed', models.PositiveIntegerField(default=0)),
                ('revenue_generated', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Performance',
                'verbose_name_plural': 'User Performance Reports',
                'ordering': ['-period_start'],
                'indexes': [models.Index(fields=['user', 'period_start', 'period_end'], name='analytics_u_user_id_38d745_idx')],
                'unique_together': {('user', 'period_start', 'period_end')},
            },
        ),
    ]
