# Generated by Django 5.2.7 on 2025-11-11 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_calendarevent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CalendarEvent',
        ),
    ]
