# Generated by Django 5.2.7 on 2025-11-11 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0001_initial'),
    ]

    operations = [
    ]
